### ISSUE TITLE
No error handling directive

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#947] opened 2022-02-25 15:30 UTC
Not sure why the following block is tripping the 'no error handling directive rule':
````
REPEAT
   ON STOP   UNDO, RETRY
   ON ERROR  UNDO, RETRY
:
   // false positive
END.
````
If the ``on stop`` is removed:
````
REPEAT
   ON ERROR  UNDO, RETRY
:
   // ok
END.
````
Or the ``on error`` is moved to before ``on stop``:
````
REPEAT
   ON ERROR  UNDO, RETRY
   ON STOP   UNDO, RETRY
:
   // ok
END.
````
Then the rule is happy.

**Comment by gquerret** [comment] 2022-02-28 08:14
Reproduced ! It looks like a change in the syntax tree introduced this regression, the bad pattern was incorrectly detected by the rule.

**Comment by gquerret** [comment] 2022-04-06 19:23
Fixed in develop

**Closed by gquerret** 2022-04-06 19:23 UTC
Labels: False positive
