### ISSUE TITLE
PDSOE 12.7: View rule description: unknown protocol: data

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#1056] opened 2023-06-27 08:43 UTC
When using PDSOE 12.7 and attempting to view a rule description from the SonarLint On-The-Fly view, an error occurs:

````
Unable to open URL: data:text/html;charset=utf-8;base64,PCFkb2N0eXBlIGh0bWw+PGh0bWw+PGhlYWQ+PHN0eWxlIHR5cGU9InRleHQvY3NzIj5ib2R5IHsgZm9udC1mYW1pbHk6IEhlbHZldGljYSBOZXVlLFNlZ29lIFVJLEhlbHZldGljYSxBcmlhbCxzYW5zLXNlcmlmOyBmb250LXNpemU6IDEwcHQ7IGNvbG9yOiByZ2JhKDAsIDAsIDAsIDEuMCk7YmFja2dyb3VuZC1jb2xvcjogcmdiYSgyNTUsIDI1NSwgMjI1LCAxLjApO31oMSB7IG1hcmdpbi1ib3R0b206IDA7IGZvbnQtc2l6ZTogMTUwJSB9aDEgLnJ1bGVuYW1lIHsgZm9udC13ZWlnaHQ6IGJvbGQ7IH1oMSAucnVsZWtleSB7IGZvbnQtd2VpZ2h0OiBub3JtYWw7IGZvbnQtc2l6ZTogc21hbGxlcjt9aDIgeyBmb250LXNpemU6IDEyMCUgfWltZyB7IGhlaWdodDogMTFwdDsgd2lkdGg6IDExcHQ7IHZlcnRpY2FsLWFsaWduOiBtaWRkbGU7IH0udHlwZXNldmVyaXR5IHNwYW4geyBmb250LXNpemU6IDFlbTsgbWFyZ2luLWxlZnQ6IDAuNWVtOyBtYXJnaW4tcmlnaHQ6IDFlbTt9ZGl2LnR5cGVzZXZlcml0eSB7IHBhZGRpbmc6IDA7IG1hcmdpbjogMH1hIHsgYm9yZGVyLWJvdHRvbTogMXB4IHNvbGlkIHJnYmEoMCwgMTAyLCAyMDQsIDEuMCk7IGNvbG9yOiByZ2JhKDAsIDEwMiwgMjA0LCAxLjApOyBjdXJzb3I6IHBvaW50ZXI7IG91dGxpbmU6IG5vbmU7IHRleHQtZGVjb3JhdGlvbjogbm9uZTt9YTpob3ZlciB7IGNvbG9yOiByZ2JhKDAsIDcxLCAxNDMsIDEuMCl9Y29kZSB7IHBhZGRpbmc6IC4yZW0gLjQ1ZW07IG1hcmdpbjogMDsgYmFja2dyb3VuZC1jb2xvcjogcmdiYSgwLCAwLCAwLCAwLjE5NjA3ODQzMTM3MjU0OTAyKTsgYm9yZGVyLXJhZGl1czogM3B4OyB3aGl0ZS1zcGFjZTogbm93cmFwOyBsaW5lLWhlaWdodDogMS42ZW19cHJlIHsgcGFkZGluZzogLjdlbTsgYm9yZGVyLXRvcDogMXB4IHNvbGlkIHJnYmEoMCwgMCwgMCwgMC43ODQzMTM3MjU0OTAxOTYxKTsgYm9yZGVyLWJvdHRvbTogMXB4IHNvbGlkIHJnYmEoMCwgMCwgMCwgMC4zOTIxNTY4NjI3NDUwOTgwMyk7IG92ZXJmbG93OiBhdXRvO31jb2RlLCBwcmUgeyBmb250LWZhbWlseTogQ29uc29sYXMsTGliZXJhdGlvbiBNb25vLE1lbmxvLENvdXJpZXIsbW9ub3NwYWNlO311bCB7IHBhZGRpbmctbGVmdDogMi41ZW07IGxpc3Qtc3R5bGU6IGRpc2M7fS5ydWxlLWRlc2MgeyBsaW5lLWhlaWdodDogMS41ZW0gfTwvc3R5bGU+PC9oZWFkPjxib2R5PjxzbWFsbD48ZW0+KE5vIHJ1bGVzIHNlbGVjdGVkKTwvZW0+PC9zbWFsbD48L2JvZHk+PC9odG1sPg==
java.net.MalformedURLException: unknown protocol: data
	at java.base/java.net.URL.<init>(URL.java:681)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at org.sonarlint.eclipse.ui.internal.util.SonarLintWebView$1.changing(SonarLintWebView.java:180)
	at org.eclipse.swt.browser.Edge.handleNavigationStarting(Edge.java:575)
	at org.eclipse.swt.browser.Edge.handleNavigationStarting(Edge.java:557)
	at org.eclipse.swt.browser.Edge.lambda$5(Edge.java:197)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3630)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
````

Based on [Eclipse bug 538991](https://git.eclipse.org/r/c/platform/eclipse.platform.swt/+/174084) I am guessing that this is a result of Edge now being used in Eclipse instead of Internet Explorer. When starting PDSOE 12.7 'Found Edge' flashes by in the console.

But I am lost as to where this problem needs to be addressed:
- Progress?
- SonarQube?
- Riverside?

**Comment by gquerret** [comment] 2023-06-27 08:57
Do you use SonarLint 7.6.2312 ?
If so, I'll try to reproduce the problem with 12.7. It's probably coming from the base version of SonarLint but that has to be verified.

**Comment by stefandrissen** [comment] 2023-06-27 10:43
Hmmm... I was using 5.2.1.RSSW. My SonarQube server version is 8.9.

I have now updated to SonarLint 7.6.2312 - issue remains, error log seems slightly different:

````
Unable to open external browser
java.net.MalformedURLException: unknown protocol: data
	at java.base/java.net.URL.<init>(URL.java:681)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at org.sonarlint.eclipse.ui.internal.util.BrowserUtils.lambda$0(BrowserUtils.java:34)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4035)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3635)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
````

**Comment by gquerret** [comment] 2023-06-28 08:21
Reproduced in 12.7. Further investigation needed...

**Comment by gquerret** [comment] 2023-06-29 13:20
It seems to be related to the Eclipse version being used by Progress, because the same SL plugin works well on my 2023-03 version of Eclipse. I'll get in touch with Progress. I've unfortunately not found any workaround for now.

**Comment by stefandrissen** [comment] 2023-06-29 13:44
The Eclipse version is not the problem. Progress is tailoring (see launchPDSOE.bat) eclipse.ini to use Edge as default browser:
````
-Dorg.eclipse.swt.browser.DefaultType="edge"
````
This was probably added to ensure that the Eclipse Welcome screen (and the subsequent web links) are rendered nicely.

**Comment by gquerret** [comment] 2023-12-18 09:07
Additional investigation done, but without any noticable improvement. Issue will be flagged as Won't fix, documentation has been updated to show how to fix the issue.  Progress also didn't find anything, and they want to keep Edge as the default browser.
SonarLint 9.1.2900 will be released soon.

**Closed by gquerret** 2023-12-18 09:07 UTC
Labels: sonarlint
