### ISSUE TITLE
WHOLE-INDEX on Temp-Table on FOR EACH <temp-table>

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#116] opened 2016-11-27 21:50 UTC
I do not think that a FOR EACH <temp-table> with no selection criteria should alert for WHOLE-INDEX query.

Temp-Tables are typically used to contain pre-selected data - which then very often is processed without any need for further selection. Alterting this as a problematic WHOLE-INDEX access is in my eyes a false positive.

WHOLE index access on temp-table should only be reported when selection or sort criteria does not match any index. But not when no sort or selection is specified.

Same should appy to a FIND FIRST <temp-table> without any further criteria.

**Comment by movedoa** [comment] 2016-11-28 07:32
Is this a duplicate of https://github.com/Riverside-Software/sonar-openedge/issues/100?

**Comment by mikefechner** [comment] 2016-11-28 07:41
Different symptoms. But related. Yes.

Sent from Nine<http://www.9folders.com/>
________________________________
Von: movedoa <notifications@github.com>
Gesendet: 28.11.2016 8:33 vorm.
An: Riverside-Software/sonar-openedge
Cc: Mike Fechner; Author
Betreff: Re: [Riverside-Software/sonar-openedge] WHOLE-INDEX on Temp-Table on FOR EACH <temp-table> (#116)


Is this a duplicate of #100<https://github.com/Riverside-Software/sonar-openedge/issues/100>?

-

**Comment by gquerret** [comment] 2016-12-01 08:10
As Mike said, not exactly a duplicate, but enough to keep a single issue opened. So closing as a duplicate of #100 .

**Closed by gquerret** 2016-12-01 08:10 UTC
