### ISSUE TITLE
Question: how to deal with common includes

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#725] opened 2019-09-12 21:56 UTC
We have two top level projects (bl and ui) which use a common include project (i).

The propaths of the two top level projects reference the include project. Compile time / run time everything is fine.

But how do I tell SonarQube to process the include files?

````
[sonar:sonar] Project base dir: D:\jenkins\workspace\7.27\build work\bl
[sonar:sonar] -------------  Scan Exact Financials - bl
[sonar:sonar] Base dir: D:\jenkins\workspace\7.27\build work\bl
[sonar:sonar] Working dir: d:\jenkins\workspace\7.27\build work\bl\.sonar
[sonar:sonar] Source paths: ., d:\jenkins\workspace\7.27\build work\i, d:\jenkins\workspace\7.27\build work\cd\cd\db\progress
...
[sonar:sonar] File 'D:\jenkins\workspace\7.27\build work\i\ifall\procrepo.i' is ignored. It is not located in module basedir 'D:\jenkins\workspace\7.27\build work\bl'.
...
...
[sonar:sonar] Project base dir: D:\jenkins\workspace\7.27\build work\ui
[sonar:sonar] -------------  Scan Exact Financials - ui
[sonar:sonar] Base dir: D:\jenkins\workspace\7.27\build work\ui
[sonar:sonar] Working dir: d:\jenkins\workspace\7.27\build work\ui\.sonar
[sonar:sonar] Source paths: ., d:\jenkins\workspace\7.27\build work\i
...
[sonar:sonar] File 'D:\jenkins\workspace\7.27\build work\i\ifall\procrepo.i' is ignored. It is not located in module basedir 'D:\jenkins\workspace\7.27\build work\ui'.
````

The files are /not/ in the basedir, they're in a sibling of the basedir, but they really need to be scanned.

**Comment by gquerret** [comment] 2019-09-13 07:48
As mentioned in the log, SonarQube ignores directories not under base directory. You can still include them in sonar.oe.propath so that code parsing can be done correctly, but you won't see their content in the web UI. If you really want to see them, I'd say that you should copy (or create a link) in the base directory, then add the directory to sonar.sources.

```
<root>
    inc/
      sub/
        include01.i
        ....
    bl/
      inc -> ../inc
      src
    ui/
      inc -> ../inc
      src
```

When analyzing bl, then set `sonar.sources=src,inc` and `sonar.oe.propath=src,inc`

**Comment by stefandrissen** [comment] 2019-09-13 20:30
Thanks for your reply. I am still not there.. My sources are located directly below my project folders, there is no intermediate src folder, so I am unable to put the include sources next to the bl / ui sources at the same level.
````
bl/file.p
i/file.i
ui/file.p
````
When I copy i /into/ ui, the sources are shown in web interface, but not analyzed (I think their reference is incorrect - when compiled they were compiled from ../i and not ./i):
````
bl/file.p
bl/i/file.i
````
I cannot use bl,bl/i as sonar.sources since SonarQube then complains about duplicate files.

Any other options?

**Comment by gquerret** [comment] 2019-09-15 16:21
Do you execute the first analysis from the bl/ directory and the second one from ui/ ?

**Comment by stefandrissen** [comment] 2019-09-15 20:04
Yes, bl and ui are both projects, as is i. Both bl and ui have themselves + i in their propath.

As a last resort I think I can cheat and copy sources from i directly into bl and ui when compiling and analyzing, it's just a bit messy.

**Comment by gquerret** [comment] 2019-09-16 06:24
It might be possible to start the analysis from the parent directory, and then use `sonar.sources=bl,i`. You'll have to update a few properties (especially propath). The problem is that you'll lose the 'Won't fix' or 'False positives' markers on issues, as SQ will consider that they are new files. Do you have a single code repo for the 3 projects, or 3 different repo ?
The second option is to copy the .i in bl and ui, as that won't break the WF and FP markers. A bit messy, as you said.

**Comment by stefandrissen** [comment] 2019-09-16 09:48
I'm using the ui project as example, since it is tiny compared to bl. I've changed the sonar properties to:
````
<property name="sonar.projectBaseDir" value=".." />
<property name="sonar.sources" value="ui,i" />
<property name="sonar.oe.propath" value="ui,i" />
````
There are no warnings from sonar anymore about skipped files, all files are available in the web interface **but** there are no analysis results on the files from the i directory. I expect that this is due to the mismatch between the propath used at compile time ( .,../i ) and the different propath at scan time ( ui,i ).

If I change the propath to what it was when compiled ( .,../i ) then sonar cannot find the includes:

````
[sonar:sonar] Unable to parse ui/ifall/procrepo.p - Can't find include file 'ifall/general/ifdefs.client.i' from 'ui/ifall/procrepo.p'
````
I'm not sure what you mean with a single code repo - the projects are all siblings within the same tfs collection, they are compiled separately.

I'll have another look at copying both folders to a separate folder in which they are merged and see what happens when that is analyzed.

**Comment by stefandrissen** [comment] 2019-09-16 10:04
Copying both folders to a separate 'tmp.sonar' folder and using this as sonar.projectBaseDir, while a bit clunky, gets the job done.

````
<copy todir="tmp.sonar">
	<fileset dir="." />
	<fileset dir="../i" />
</copy>
...
<property name="sonar.projectBaseDir" value="tmp.sonar" />
...
<property name="sonar.sources" value="." />
<property name="sonar.exclusions" value="tmp.sonar" />
...
<property name="sonar.oe.propath" value="." />
...
<sonar:sonar />
<delete dir="tmp.sonar"/>
````

**Closed** 2019-09-16 10:04 UTC
