### ISSUE TITLE
Big nested DO! ERROR: Error during rule execution for ... JPNode cannot be cast to class org.prorefactor.core.nodetypes.FieldRefNode 

### ISSUE THREAD

**Issue by Tranborg** [Riverside-Software/sonar-openedge#982] opened 2022-08-01 11:14 UTC
Yes this big nested DO is needed. Sorry.

------------------------
     [exec] ERROR: Error during rule execution for src/MainMenu/GeneralLedger/beDrilldownBookedBalance.cls
     [exec] java.lang.ClassCastException: class org.prorefactor.core.JPNode cannot be cast to class org.prorefactor.core.nodetypes.FieldRefNode (org.prorefactor.core.JPNode and org.prorefactor.core.nodetypes.FieldRefNode are in unnamed module of loader org.sonar.classloader.ClassRealm @5f4d427e)
     [exec] 	at eu.rssw.antlr.proparse.checks.NestedDo.execute(Unknown Source)
     [exec] 	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.sensorExecute(OpenEdgeProparseCheck.java:57)
     [exec] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:401)
     [exec] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:176)
     [exec] 	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
     [exec] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
     [exec] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
     [exec] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
     [exec] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
     [exec] 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
     [exec] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
     [exec] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
     [exec] 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:392)
     [exec] 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:388)
     [exec] 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:357)
     [exec] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
     [exec] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
     [exec] 	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:150)
     [exec] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
     [exec] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
     [exec] 	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
     [exec] 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
     [exec] 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
     [exec] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
     [exec] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
     [exec] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
     [exec] 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
     [exec] 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
     [exec] 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
     [exec] 	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
     [exec] 	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
     [exec] 	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
     [exec] 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

from code-------------------------------------------------------
```
        LOOP:
        DO ind-ftg = 1 TO ent-ftg:
            IF ent-ftg > 1 THEN i-ftgid = ENTRY(ind-ftg,iCompany).
            DO ind-enhet = 1 TO ent-enhet:
                IF ent-enhet > 1 THEN i-enhet = ENTRY(ind-enhet,iEntity).
                DO ind-affval = 1 TO ent-affval:
                    IF ent-affval > 1 THEN i-affval = ENTRY(ind-affval, iDealCurrency).
                    DO ind-bokfval = 1 TO ent-bokfval:
                        IF ent-bokfval > 1 THEN i-bokfval = ENTRY(ind-bokfval, iBookCurrency).
                        DO ind-serie = 1 TO ent-serie:
                            IF ent-serie > 1 THEN i-serie = ENTRY(ind-serie, iSeries).
                            DO ind-kontodel[1] = 1 TO ent-kontodel[1]:
                                IF ent-kontodel[1] > 1 THEN i-kontodel[1] = ENTRY(ind-kontodel[1], iAccountPart[1]).
                                DO ind-kontodel[2] = 1 TO ent-kontodel[2]:
                                    IF ent-kontodel[2] > 1 THEN i-kontodel[2] = ENTRY(ind-kontodel[2], iAccountPart[2]).
                                    DO ind-kontodel[3] = 1 TO ent-kontodel[3]:
                                        IF ent-kontodel[3] > 1 THEN i-kontodel[3] = ENTRY(ind-kontodel[3], iAccountPart[3]).
                                        DO ind-kontodel[4] = 1 TO ent-kontodel[4]:
                                            IF ent-kontodel[4] > 1 THEN i-kontodel[4] = ENTRY(ind-kontodel[4], iAccountPart[4]).
                                            DO ind-kontodel[5] = 1 TO ent-kontodel[5]:
                                                IF ent-kontodel[5] > 1 THEN i-kontodel[5] = ENTRY(ind-kontodel[5], iAccountPart[5]).
                                                DO ind-kontodel[6] = 1 TO ent-kontodel[6]:
                                                    IF ent-kontodel[6] > 1 THEN i-kontodel[6] = ENTRY(ind-kontodel[6], iAccountPart[6]).
                                                    DO ind-kontodel[7] = 1 TO ent-kontodel[7]:
                                                        IF ent-kontodel[7] > 1 THEN i-kontodel[7] = ENTRY(ind-kontodel[7], iAccountPart[7]).
                                                        DO ind-kontodel[8] = 1 TO ent-kontodel[8]:
                                                            IF ent-kontodel[8] > 1 THEN i-kontodel[8] = ENTRY(ind-kontodel[8], iAccountPart[8]).
                                                            DO ind-kontodel[9] = 1 TO ent-kontodel[9]:
                                                                IF ent-kontodel[9] > 1 THEN i-kontodel[9] = ENTRY(ind-kontodel[9], iAccountPart[9]).
                                                                DO ind-kontodel[10] = 1 TO ent-kontodel[10]:
                                                                    IF ent-kontodel[10] > 1 THEN i-kontodel[10] = ENTRY(ind-kontodel[10], iAccountPart[10]).

                                                                    
                                                                    RUN getsaldo IN xGetSaldoHandle ("UB":U, i-bokfdat, i-ftgid, i-enhet, i-serie, i-boktyper, i-affval, i-bokfval, i-kontodel, iAccountPartSpec, OUTPUT o-affsaldo, OUTPUT o-bokfsaldo).
                                                                                
                                                                    IF NOT iShowZeroResult AND o-affsaldo = 0 AND o-bokfsaldo = 0 THEN NEXT.
                                                                    w-kontostr = "".
                                                                    DO  i = 1 TO 10:
                                                                        w-kontodel = i-kontodel[i].
                                                                        IF NUM-ENTRIES(w-kontodel) > 1 THEN
                                                                            w-kontodel = "(":U + w-kontodel + ")":U.
                                                                        ELSE
                                                                            w-kontodel = w-kontodel + ".":U.
                                                                        w-kontostr = w-kontostr + w-kontodel.   
                                                                    END.
                                                                    w-kontostr = RIGHT-TRIM(w-kontostr,". ":U).

                                                                    FIND FIRST ttDrilldownBookedBalanceSource WHERE ttDrilldownBookedBalanceSource.BookDate = i-bokfdat
                                                                        AND ttDrilldownBookedBalanceSource.Company      = i-ftgid
                                                                        AND ttDrilldownBookedBalanceSource.Entity       = i-enhet
                                                                        AND ttDrilldownBookedBalanceSource.DealCurrency = i-affval
                                                                        AND ttDrilldownBookedBalanceSource.BookCurrency = i-bokfval
                                                                        AND ttDrilldownBookedBalanceSource.Series       = i-serie
                                                                        AND ttDrilldownBookedBalanceSource.AccountString = w-kontostr NO-ERROR.
                                                                    
                                                                    IF AVAILABLE ttDrilldownBookedBalanceSource THEN NEXT.
                                                                
                                                                    CREATE ttDrilldownBookedBalanceSource.
                                                                    ASSIGN
                                                                        locSeq                                                      = locSeq + 1
                                                                        ttDrilldownBookedBalanceSource.seq                          = locSeq
                                                                        ttDrilldownBookedBalanceSource.BookDate                     = i-bokfdat
                                                                        ttDrilldownBookedBalanceSource.Company                      = i-ftgid
                                                                        ttDrilldownBookedBalanceSource.Entity                       = i-enhet
                                                                        ttDrilldownBookedBalanceSource.DealCurrency                 = IF NUM-ENTRIES(i-affval) = 1 THEN i-affval ELSE ""
                                                                        ttDrilldownBookedBalanceSource.BookCurrency                 = IF NUM-ENTRIES(i-bokfval) = 1 THEN i-bokfval ELSE ""
                                                                        ttDrilldownBookedBalanceSource.Series                       = i-serie
                                                                        ttDrilldownBookedBalanceSource.AccountingType               = (IF NUM-ENTRIES(i-boktyper) = 1 THEN INTEGER(i-boktyper) ELSE 0)
                                                                        ttDrilldownBookedBalanceSource.AccountString                = w-kontostr
                                                                        ttDrilldownBookedBalanceSource.ClosingBalanceInDealCurrency = IF NUM-ENTRIES(i-affval) = 1 THEN o-affsaldo ELSE 0
                                                                        ttDrilldownBookedBalanceSource.ClosingBalanceInBookCurrency = IF NUM-ENTRIES(i-bokfval) < 2 THEN o-bokfsaldo ELSE 0
                                                                        ttDrilldownBookedBalanceSource.AccountPart1                 = i-kontodel[1]
                                                                        ttDrilldownBookedBalanceSource.AccountPart2                 = i-kontodel[2]
                                                                        ttDrilldownBookedBalanceSource.AccountPart3                 = i-kontodel[3]
                                                                        ttDrilldownBookedBalanceSource.AccountPart4                 = i-kontodel[4]
                                                                        ttDrilldownBookedBalanceSource.AccountPart5                 = i-kontodel[5]
                                                                        ttDrilldownBookedBalanceSource.AccountPart6                 = i-kontodel[6]
                                                                        ttDrilldownBookedBalanceSource.AccountPart7                 = i-kontodel[7]
                                                                        ttDrilldownBookedBalanceSource.AccountPart8                 = i-kontodel[8]
                                                                        ttDrilldownBookedBalanceSource.AccountPart9                 = i-kontodel[9]
                                                                        ttDrilldownBookedBalanceSource.AccountPart10                = i-kontodel[10]
                                                                        ttDrilldownBookedBalanceSource.RowColor                     = "blue"
    
                                                                        ack-bokfbel                                                 = (ack-bokfbel + o-bokfsaldo)
                                                                        ack-affbel                                                  = (ack-affbel + o-affsaldo)
                                                                        .
                                                                
                                                                    IF jamf-bokfval = "" THEN jamf-bokfval = ttDrilldownBookedBalanceSource.BookCurrency.
                                                                    IF jamf-bokfval <> ttDrilldownBookedBalanceSource.BookCurrency OR num-entries(i-bokfval) > 1 THEN nobokfbel = TRUE.
                                                                    IF jamf-affval = "" THEN jamf-affval = ttDrilldownBookedBalanceSource.DealCurrency.
                                                                    IF jamf-affval <> ttDrilldownBookedBalanceSource.DealCurrency THEN noaffbel = TRUE.
                                                                END.
                                                            END.
                                                        END.
                                                    END.
                                                END.
                                            END.
                                        END.
                                    END.
                                END.
                            END.
                        END.
                    END.
                END.
            END.
        END.
```

**Comment by gquerret** [comment] 2022-08-01 11:21
Duplicate of #976. Problem has already been identified, and will be fixed in next version.
Anyway, thanks for the example !

**Closed by gquerret** 2022-08-01 11:21 UTC

**Comment by Tranborg** [comment] 2022-08-01 11:38
Got it! I just found the other when I was adding this. Nice tool this is. :)
