### ISSUE TITLE
Unexpected token: DEFINE (include file)

### ISSUE THREAD

**Issue by jcromanu** [Riverside-Software/sonar-openedge#590] opened 2018-10-08 20:56 UTC
I got an unexpected token error when parsing the DEFINE in the following code on an include file : 

```
&SCOPED-DEFINE version PUII-20170831-001
&SCOPED-DEFINE extent 100
&SCOPED-DEFINE format "X(250)"

&IF {&include} &THEN
    DEFINE VARIABLE vChrTrajecI   AS CHARACTER NO-UNDO EXTENT {&extent} FORMAT {&format}.
```

**Comment by gquerret** [comment] 2018-10-08 21:14
Can you include the log message and stack trace ?

**Comment by jcromanu** [comment] 2018-10-08 21:41
Here is the stack-trace

`ERROR: Error during code parsing for Appserver/crdlcp2-p.p at position iobteninfo.i:18:5
antlr.NoViableAltException: unexpected token: DEFINE
	at org.prorefactor.proparse.ProParser.expression_statement(ProParser.java:1691)
	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:399)
	at org.prorefactor.proparse.ProParser.program(ProParser.java:133)
	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:197)
	at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:229)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:264)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:176)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:177)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:291)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:286)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:264)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)`

**Comment by gquerret** [comment] 2018-10-09 14:32
There must be something else, if I copy / paste your code snippet in a new file, that doesn't produce any exception.

**Comment by jcromanu** [comment] 2018-10-10 21:07
Lets call "nestedfile.i" to the file which contains the previous code .
This nestedfile.i file is invoked on another include file , lets call this "reference.i" in  the following way . 
`{nestedfile.i &programm = 'anotherfile.i'}
`
Basically we are including an include file on another include file .
The nestedfile.i does not contains a BOM or something special .

**Comment by gquerret** [comment] 2018-10-11 13:08
Sorry, unable to reproduce. Can you reproduce the problem on the sonaroe-test-project ? If so, please push it to your personal fork of the project.

**Comment by jcromanu** [comment] 2018-10-18 21:10
Still trying to reproduce the error using the sample test.

**Comment by gquerret** [comment] 2019-01-30 08:44
Were you able to reproduce ? Otherwise, I'll close the issue.

**Closed** 2019-02-05 08:00 UTC
