### ISSUE TITLE
too many function calls in one procedure results in java.lang.StackOverflowError

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#746] opened 2019-10-21 09:09 UTC
Since updating to 2.6.0 from 2.4.0 our SonarQube build is failing with a java.lang.StackOverflowError.

````
d:\jenkins\workspace\7.27\build work\bl\build.xml:486: java.lang.StackOverflowError
	at org.prorefactor.core.JPNode$Builder.build(JPNode.java:1026)
	at org.prorefactor.core.JPNode$Builder.build(JPNode.java:1040)
	at org.prorefactor.core.JPNode$Builder.build(JPNode.java:1040)
	at org.prorefactor.core.JPNode$Builder.build(JPNode.java:1040)
	at org.prorefactor.core.JPNode$Builder.build(JPNode.java:1040)
	at org.prorefactor.core.JPNode$Builder.build(JPNode.java:1040)
	at org.prorefactor.core.JPNode$Builder.build(JPNode.java:1026)
	at org.prorefactor.core.JPNode$Builder.build(JPNode.java:1026)
	at org.prorefactor.core.JPNode$Builder.build(JPNode.java:1040)
````
followed by another approx 1000 counts from line 1040 (total 1024).

I added the -v option to the build to identify the file this is crashing on (sttran.en-us.p), it contains approx 8000 (void) function calls which look something like:

````
createTerm(     77, "",              "PayRef":u ).
````
SonarLint also instantly throws a stackoverflow when opening this file.

**Comment by gquerret** [comment] 2019-10-21 09:11
Duplicate of https://github.com/Riverside-Software/sonar-openedge/issues/689

**Closed by gquerret** 2019-10-21 09:11 UTC

**Comment by stefandrissen** [comment] 2019-10-21 09:19
thanks, setting -Xss4m solved the issue
