### ISSUE TITLE
Could not resolve table: tt_before (inherited from parent)

### ISSUE THREAD

**Issue by laumingis** [Riverside-Software/sonar-openedge#323] opened 2017-08-07 10:58 UTC
Sonar parser is not able to resolve tt_before buffer, which is defined in the parent.

**Parent.cls:**
```
CLASS Parent:
    DEFINE PROTECTED TEMP-TABLE tt NO-UNDO
        BEFORE-TABLE tt_before
        FIELD id AS INT64
        .
END CLASS.
```
**Child.cls:**
```
CLASS Child INHERITS Parent:
    METHOD saveData:
        FOR EACH tt_before WHERE ROW-STATE(tt_before) > ROW-UNMODIFIED:
            /* ... */
        END.
    END METHOD.
END CLASS.
```

Sonar reports this error:
```
org.prorefactor.treeparser.TreeParserException: /.../Child.cls:3 Could not resolve table: tt_before
```

**Comment by gquerret** [comment] 2017-08-07 11:31
Duplicate of #134 
First set of changes were introduced in 2.0.3 to handle this missing functionality ; in short, information is read from rcode so that reliable structure can be available even if source is not there.

**Closed by gquerret** 2017-08-07 11:31 UTC
