### ISSUE TITLE
Proparse error - expecting LEFTPAREN, found '.' -> DYNAMIC-NEW lcProgName().

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#19] opened 2016-05-12 12:34 UTC
The following code creates the proparse error "expecting LEFTPAREN, found '.'  "

loVariable = DYNAMIC-NEW lcProgName().

**Comment by jakejustus** [comment] 2016-05-25 13:19
Do you have a bit more context, I'm currently unable to reproduce the issue.

**Comment by movedoa** [comment] 2016-05-25 13:58
I have sent you an email with an example.

**Comment by jakejustus** [comment] 2016-05-25 15:27
Reproduced, that only happens when the dynamic-new is inside a method (not from a procedure).

**Comment by jakejustus** [comment] 2016-05-25 16:16
Fixed in dev

**Closed by jakejustus** 2016-05-25 16:16 UTC
