### ISSUE TITLE
Unexpected token : .

### ISSUE THREAD

**Issue by samixchoumi** [Riverside-Software/sonar-openedge#252] opened 2017-05-19 14:55 UTC
Got this error : 
`C:\User\workspace\BUILD46.06\temp\src\stplbdyn.i02:97:48: unexpected token: .`
The line corresponding : 
`DEFINE BUFFER bgm_main_table  FOR {&MAIN_TABLE}.`

and some time i got an error about unknown table name but it's not directly called on the function, it's called with an include.

What's the fact ? I got this error some time but don't know how to prevent this

**Comment by jurjendijkstra-vma** [comment] 2017-05-19 15:05
I bet main_table is not defined (or defined blank), can you verify that?

**Comment by samixchoumi** [comment] 2017-05-19 15:14
Define here : 
`&GLOBAL-DEFINE VALIDATE_MAIN_TABLE     VALIDATE blm_main_table NO-ERROR. ~`
and define here for the buffer : 
`DEFINE          PARAMETER BUFFER blm_main_table FOR {&MAIN_TABLE}.`

**Comment by gquerret** [comment] 2017-05-19 15:30
This doesn't define {&MAIN_TABLE} but {&VALIDATE_MAIN_TABLE}
As Jurjen said, the preprocessor variable MAIN_TABLE is not defined.

**Comment by jurjendijkstra-vma** [comment] 2017-05-19 16:18
I am guessing that includefile stplbdyn.i usually gets included in a compilation unit ( a .p or .w or .cls, anything that compiles into a .r) and that main_table is defined in the including .p.
Includefiles often can not compile as an independent file because they depend on the context of the compilation unit they are in. And: if a file cannot be compiled, then it can also not be parsed.

I guess that a SonarQube sensor is trying to proparse the includefile independently, not for lint rules but only to search for duplicated code or maybe other metrics, like line count or comments count. Could that be what's happening, Gilles? Just curious myself, trying to grasp how it is working.

**Comment by gquerret** [comment] 2017-05-19 17:19
Include files are only lex'ed, not parsed, in order to compute metrics like lines and comments count, but also for the copy/paste detector (CPD).
So the error should probably happen when the include file is parsed from a main .p or .cls, and where the preprocessor variable is not defined. **If** the file can be compiled with the compiler, then it may be a preprocessor bug

**Comment by gquerret** [comment] 2017-05-19 17:19
A stack trace as well as a simple example would also be very useful in order to find the issue.

**Comment by samixchoumi** [comment] 2017-05-22 07:20
Here is a stack trace
```
[sonar:sonar] 16:33:23.713 ERROR - Error during code parsing for stplbdyn.i02
[sonar:sonar] org.prorefactor.refactor.RefactorException: C:\User\workspace\BUILD_46.06\temp\src\stplbdyn.i02:97:48: unexpected token: .
[sonar:sonar] 	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:162)
[sonar:sonar] 	at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:189)
[sonar:sonar] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:185)
[sonar:sonar] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:136)
[sonar:sonar] 	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
[sonar:sonar] 	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
[sonar:sonar] 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
[sonar:sonar] 	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
[sonar:sonar] 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
[sonar:sonar] 	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
[sonar:sonar] 	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
[sonar:sonar] 	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
[sonar:sonar] 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
[sonar:sonar] 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:77)
[sonar:sonar] 	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
[sonar:sonar] 	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
[sonar:sonar] 	at java.security.AccessController.doPrivileged(Native Method)
[sonar:sonar] 	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
[sonar:sonar] 	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
[sonar:sonar] 	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
[sonar:sonar] 	at org.sonar.runner.api.Runner.execute(Runner.java:100)
[sonar:sonar] 	at org.sonar.ant.SonarTask.launchAnalysis(SonarTask.java:53)
[sonar:sonar] 	at org.sonar.ant.SonarTask.execute(SonarTask.java:48)
[sonar:sonar] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
[sonar:sonar] 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[sonar:sonar] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[sonar:sonar] 	at org.apache.tools.ant.Target.execute(Target.java:390)
[sonar:sonar] 	at org.apache.tools.ant.Target.performTasks(Target.java:411)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
[sonar:sonar] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
[sonar:sonar] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
[sonar:sonar] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
[sonar:sonar] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
[sonar:sonar] 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[sonar:sonar] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[sonar:sonar] 	at org.apache.tools.ant.Target.execute(Target.java:390)
[sonar:sonar] 	at org.apache.tools.ant.Target.performTasks(Target.java:411)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
[sonar:sonar] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
[sonar:sonar] 	at org.apache.tools.ant.Main.runBuild(Main.java:809)
[sonar:sonar] 	at org.apache.tools.ant.Main.startAnt(Main.java:217)
[sonar:sonar] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
[sonar:sonar] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
[sonar:sonar] Caused by: antlr.NoViableAltException: unexpected token: .
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.definebufferstate(ProParser.java:35836)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.definestatement(ProParser.java:7334)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.statement(ProParser.java:2115)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:422)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.program(ProParser.java:154)
[sonar:sonar] 	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:151)
[sonar:sonar] 	... 65 common frames omitted
```

**Comment by movedoa** [comment] 2017-05-22 11:08
Same error here in many cases.
The include statement is like {Root/i/{&SysInclude}.i}

I get the error: Could not find include file: Root/i/.i
I looked at one case and here the error happens in an include that includes another include (horrible legacy code i know)

The preprocessor is defined in the include where the error happens but with a parameter like:
&Scoped-define SysInclude {1}

**Comment by gquerret** [comment] 2017-05-22 11:27
@movedoa Very interesting test case, I'll try to reproduce as a unit test.
Given your example, it's possible there's an issue with preprocessor variables not expanded in include file reference.

**Comment by movedoa** [comment] 2017-05-22 14:11
Yes

**Comment by gquerret** [comment] 2017-05-22 14:36
There's probably a subtle difference, this test case works perfectly !

**Comment by movedoa** [comment] 2017-05-22 14:44
I looked at it again, the small differences i see are:

- My program ist a .w file and not a .p
- The SysInclude Parameter is not the only one, it is the third one of 6 in total so it is &Scoped-define SysInclude {3}
- The include that is included over parameters has some strange quotation marks: {"$dlciss\$adrsys\i\{&SysInclude }".i "FIND-CDE":U "{&SbrTblNam}"}

**Comment by samixchoumi** [comment] 2017-05-23 09:01
Just a question, nothing exist for include ? (like a properties) (i don't speak about library) because i've some error about include file that include other include files.
A properties like `sonar.oe.aliases` could be very usefull for include file ( ==> `sonar.oe.include`)

**Comment by gquerret** [comment] 2017-05-23 09:09
Already answered in #251, the property is `sonar.oe.propath`

**Comment by samixchoumi** [comment] 2017-05-23 10:16
So i used the propath properties : 
```
<property name="sonar.oe.propath" value="C:/User/workspace/BUILD46.06/temp/src/sterrsta.i01,
C:/User/workspace/BUILD46.06/temp/src/errnotra.i01
```
Got the same error : 
`[sonar:sonar] 12:10:48.285 ERROR - Runtime exception was caught 'java.io.IOException: C:\User\workspace\BUILD46.06\temp\src\sterrsta.i01: Could not find include file: errnotra.i01' - Please report this issue : `

**Comment by gquerret** [comment] 2017-05-23 12:14
You **really** should have a look at the OpenEdge documentation (or introduction); propath is a list of directories (or PL files), not a list of files.

**Comment by gquerret** [comment] 2017-06-09 12:58
Fixed in master

**Closed by gquerret** 2017-06-09 12:58 UTC
