### ISSUE TITLE
Unexpected token: <format-phrase attribute>

### ISSUE THREAD

**Issue by stroyer** [Riverside-Software/sonar-openedge#27] opened 2016-06-20 22:37 UTC
With a .df file that defines a table with a field of the same name, format phrase attributes are not recognized as valid tokens (e.g. Unexpected token: column-label).

**example.df:**
```
ADD TABLE "currency"
ADD FIELD "currency" OF "currency" AS character   
```

**program.p:**
```
display currency.currency column-label "NewLabel".
```

sonar openedge 1.9.2, sonarqube 5.6, riverside rules 1.0.4

**Comment by jakejustus** [comment] 2016-06-21 06:37
Confirmed and reproduced

**Comment by jakejustus** [comment] 2016-06-21 08:08
Additional question : what is the .df file name ?
I was able to quickly reproduce the problem by adding a file currency.df with a table and a field (same name), and your test procedure, then add `/path/to/currency.df` in sonar.oe.databases property. In this case, the problem appears because currency.currency is recognized as the DB name followed by the table name
But after having renamed currency.df to another file name and changed (sonar.oe.databases), the problem disappears. So could you confirm what's your DF file name ?

**Comment by stroyer** [comment] 2016-06-21 15:20
My .df file is named "trading1-16.3.df".  I noticed that the error occurs anytime I have a table name in the .df file that matches the name of a field reference in a program when the field name is qualified by a table or temp-table name.  Oddly, the table or temp-table name doesn't even have to match the table name in the .df.  For example, I get the error here:

.df:
ADD TABLE "currency"

.p:
display x.currency column-label "NewLabel".

Removing the table qualifier results in successful parsing:

display currency column-label "NewLabel".

**Comment by stroyer** [comment] 2016-06-21 16:13
A variation of the above, the following statement returns "Unexpected token: [".
display custnote.notes[1].
The .df file includes a table named "notes" as well as a table named "custnote".  The custnote table includes a field called "notes" but the notes table does not have a field called "notes".  As I mentioned above, it doesn't seem to matter that the field belong to the table of the same name, just that there is a table of the same name in the .df.

**Comment by jakejustus** [comment] 2016-07-08 09:44
Fix is ready, but there may be some side effects. That won't go into the next release until some more tests are being executed.

**Comment by gquerret** [comment] 2016-07-13 08:08
Fixed in dev

**Closed by gquerret** 2016-07-13 08:08 UTC
Labels: bug
