### ISSUE TITLE
unexpected token: <> (and =) in include files with preprocessor

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#46] opened 2016-08-24 10:18 UTC
If you have something like the following  in an include you get the error.
`&IF {&sys} <> "INV":U &THEN`

The same thing with "=",">", "<" and so on:
`&IF {&sys} = "INV":U &THEN`

**Comment by gquerret** [comment] 2016-09-08 15:08
Pushed test case in branch "Issue46", but bug is not reproduced

**Comment by movedoa** [comment] 2016-09-15 21:47
That is strange, i will check if it still happens with the next version and try to provide an example if that is the case
When do you expect to release the next version?

**Comment by gquerret** [comment] 2016-09-16 07:04
Next Friday.

**Comment by movedoa** [comment] 2016-09-27 06:56
I was able to reproduce the error with the following include.

```

&IF {&SYS} <> "INV":U &THEN
   PROCEDURE Foo:
      DEFINE INPUT  PARAMETER piFoo AS INTEGER NO-UNDO.
      /* code */
   END PROCEDURE.
&ENDIF

```

**Comment by gquerret** [comment] 2016-09-27 07:58
The only way I'm able to reproduce this issue is when {&SYS} is not defined. Could you double-check where the preprocessor variable is defined ? It might be a scope issue in preprocessor variable definition, but I'd like to nail down the problem.

**Comment by movedoa** [comment] 2016-09-27 08:55
There are many places where is variable is defined.
Unfortunately this is very old (and huge) legacy code so i can't tell which of the places produces the error since i don't know the codepath that the parser is in when the error occurs.

But the code can be compiled without error so i am pretty sure the variable is defined everywhere since the include produces a compile error when the variable is undefined.

The only thing i see that maybe is problematic for the parser is that the define is in another include.
So its like:

{DefineVar.i}
/* Some Code */
{UseVar.i}

**Comment by KWSMaster** [comment] 2016-12-01 17:24
Could this be failing due to the &sys being a named parameter to the include file? The parser may not have a reference in that case, since it's part of the include syntax in the parent module.

**Comment by gquerret** [comment] 2017-01-03 15:42
Issue reproduced by a customer, but then I got the full stack trace, which led me to the right issue. This is coming from the CPD engine, not from Proparse (or not directly...).
Test case will be updated, and issue should be fixed in next release (if possible).

**Comment by gquerret** [comment] 2017-02-02 16:31
Reminder for myself: lex() shouldn't evaluate preprocessor expressions as in the parse phase

**Comment by gquerret** [comment] 2017-05-03 08:00
Fixed as part of the move to ANTRL4 for the lexer

**Closed by gquerret** 2017-05-03 08:00 UTC
Labels: bug, later
