### ISSUE TITLE
Incorrect message - "ExpressionNoEffect" for valid expression

### ISSUE THREAD

**Issue by PeterJudge-PSC** [Riverside-Software/sonar-openedge#927] opened 2021-11-23 14:20 UTC
The following line results in a rssw-oe-main:eu.rssw.antlr.proparse.checks.ExpressionNoEffect error.

`mhTempTable:default-buffer-handle:empty-temp-table.`

The issue here is that the trailing parentheses are missing. The expression does work.

OpenEdge plugin version: 2.14.4-645d363d
Sonarqube server: 7.9.5.38598

**Comment by gquerret** [comment] 2021-11-23 14:28
The current version in the develop branch already has a fix for this problem. The issue is still reported, but with a different error message, as the parenthesis are missing.

**Comment by PeterJudge-PSC** [comment] 2021-11-23 14:29
Perfect.

**Closed** 2021-11-29 15:57 UTC
