### ISSUE TITLE
Use of default buffer in LIKE with INPUT/OUTPUT Parameters 

### ISSUE THREAD

**Issue by dominickdm** [Riverside-Software/sonar-openedge#745] opened 2019-10-16 09:56 UTC
Hi,

We get a violation of the rule 'use of default buffer for Order' when we define an output parameter with a LIKE statement. 

This is a bug i suppose?

> 
> DEFINE OUTPUT PARAMETER OrderId LIKE Order.ord_Id NO-UNDO.
> 
> OrderId = 5.
> RUN nothing(OrderId).

![Sonar_error_parameter](https://user-images.githubusercontent.com/40289256/66908677-c90eaf00-f00b-11e9-8f2f-768e78ca4988.png)

**Comment by gquerret** [comment] 2020-05-06 09:22
Not able to reproduce with 2.6 and 2.7. Do you still have the problem on this code sample ?

**Comment by dominickdm** [comment] 2020-05-06 09:33
> Not able to reproduce with 2.6 and 2.7. Do you still have the problem on this code sample ?

Yes, we still have it (we are on 2.7.1). I tried also with another table, that doesn't contain the keyword (Order). 

![image](https://user-images.githubusercontent.com/40289256/81162292-3aed1c80-8f8d-11ea-96f1-92cd7a08c546.png)

**Comment by gquerret** [comment] 2020-05-06 11:21
Fixed, merged in develop

**Closed by gquerret** 2020-05-06 11:21 UTC
Labels: bug
