### ISSUE TITLE
Default Buffer Usage false positive in INPUT xxx LIKE Table.Field

### ISSUE THREAD

**Issue by bmtheo** [Riverside-Software/sonar-openedge#798] opened 2020-05-19 09:16 UTC
I suspect a false positive on the Default Buffer Usage rule (rssw-oe-main:eu.rssw.antlr.proparse.checks.BufferUsage) in that case :

FUNCTION TestType RETURNS CHARACTER (INPUT piInteger LIKE Table.Field):
    MESSAGE piInteger.
    RETURN "Hi".
END FUNCTION.

The default buffer usage is for the "LIKE Table.field"

Does it cause any trouble to do that ?

**Comment by gquerret** [comment] 2020-05-19 09:20
Duplicate of #745
Already fixed in development branch, will be available in 2.7.2 (or 2.8.x)

**Closed by gquerret** 2020-05-19 09:20 UTC
