### ISSUE TITLE
Variables referenced with @ in FRAME definitions should not be considered unused

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/sonar-openedge#1035] opened 2023-03-15 17:11 UTC
Variables used as place holder like in the sample below should not be considered unused. 

This currently triggers: Unused variables should be removed (rssw-oe-main:eu.rssw.antlr.proparse.checks.UnusedVariable)

```
BLOCK-LEVEL ON ERROR UNDO, THROW.

DEFINE VARIABLE iCustNum      AS INTEGER NO-UNDO.
DEFINE VARIABLE cCustomerName AS CHARACTER NO-UNDO.

/* ***************************  Main Block  *************************** */

FORM iCustNum cCustomerName WITH FRAME test.

FIND FIRST Customer.

DISPLAY Customer.CustNum @ iCustNum
        Customer.Name    @ cCustomerName WITH FRAME test.
```

**Comment by gquerret** [comment] 2023-03-15 18:16
Duplicate of #1019

**Comment by mikefechner** [comment] 2023-03-15 18:19
thx!

**Comment by mikefechner** [comment] 2023-03-15 18:21
Works like charm!

**Closed** 2023-03-15 18:21 UTC
