### ISSUE TITLE
Showing rule description does not work on OpenEdge 12.8

### ISSUE THREAD

**Issue by Ton-Pe** [Riverside-Software/sonar-openedge#1113] opened 2024-03-06 08:44 UTC
Show rule description does not work in SonarLint plugin. When selecting an issue from on-the-fly view and selecting Show rule description, following error is shown twice in console:

```
Unable to open external browser
java.net.MalformedURLException: unknown protocol: data
	at java.base/java.net.URL.<init>(URL.java:681)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at org.sonarlint.eclipse.ui.internal.util.BrowserUtils.lambda$0(BrowserUtils.java:45)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4035)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3635)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```
And Description view looks like this
![image](https://github.com/Riverside-Software/sonar-openedge/assets/25682299/f01ece64-37c7-417c-bc1b-c2ece1765123)

OpenEdge version 12.8.0
Tested Sonarlint plugin versions: 9.3.3006, 9.1.2906 
SonarOE plugin version on server 2.25.1.
Connection to server is OK, because updating bindings succeed.

(I do have DevStyle plugin installed for dark theme, but the error occurs on developers not using it, so that does not cause the problem).

**Comment by gquerret** [comment] 2024-03-06 08:57
Duplicate of https://github.com/Riverside-Software/sonar-openedge/issues/1056

**Closed by gquerret** 2024-03-06 08:57 UTC

**Comment by Ton-Pe** [comment] 2024-03-06 10:28
Thanks Gilles. Sorry for opening duplicate issue. I did search for the issues, but only for open issues... And seems that I should read the documentation more often too ;-)
